#!/usr/bin/env bash
#
# Regenerate the symbolic-icon set embedded in the Hylki binary.
#
# Hylki names its UI icons plainly ("edit-find-symbolic"), as GNOME apps do, so
# the user's icon theme draws every one it has (#260). The embedded GResource
# (see build.rs + src/main.rs register_resources) sits under the app's
# resource path, which GTK searches as part of hicolor, after the user's theme:
# it supplies the app's own icons, which no theme has, and GNOME's for a theme
# that lacks them, so no icon goes missing on any distro.
#
# Run this after adding/removing an icon reference in the source. It:
#   1. scans src/ for every "<name>-symbolic" string,
#   2. copies each one's SVG from Hylki's own icons (data/icons/hicolor/
#      symbolic/actions, all of which are bundled) or from Adwaita,
#   3. rewrites resources/hylki.gresource.xml to list exactly those files.
#
# An icon whose name is built at run time has to appear somewhere in full as
# well, or step 1 cannot see it.
#
# Requires: the adwaita-icon-theme package installed (for /usr/share/icons/Adwaita).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DST="$ROOT/resources/icons/scalable/actions"
CUSTOM="$ROOT/data/icons/hicolor/symbolic/actions"   # Hylki's own SVGs
ADWAITA="/usr/share/icons/Adwaita"
ADW_LIB="$(ldconfig -p | grep -om1 '/[^ ]*libadwaita[^ ]*\.so[^ ]*' || true)"

# Names referenced in the code, and every icon of Hylki's own.
mapfile -t names < <(
    {
        grep -rhoE '"[a-z0-9-]+-symbolic"' "$ROOT/src" | tr -d '"'
        for f in "$CUSTOM"/*.svg; do basename "$f" .svg; done
    } | sort -u
)

echo "==> ${#names[@]} icons: referenced in src/ or drawn for Hylki"
rm -rf "$DST"
mkdir -p "$DST"

missing=()
for n in "${names[@]}"; do
    out="$DST/$n.svg"
    if   [ -f "$CUSTOM/$n.svg" ]; then
        cp "$CUSTOM/$n.svg" "$out"
    elif f=$(find "$ADWAITA" -name "$n.svg" 2>/dev/null | head -1) && [ -n "$f" ]; then
        cp "$f" "$out"
    elif [ -n "$ADW_LIB" ] && gresource extract "$ADW_LIB" \
            "/org/gnome/Adwaita/icons/scalable/actions/$n.svg" > "$out" 2>/dev/null \
            && [ -s "$out" ]; then
        :  # sourced from libadwaita's internal resources (e.g. adw-external-link)
    else
        rm -f "$out"
        missing+=("$n")
    fi
done

if [ ${#missing[@]} -gt 0 ]; then
    echo "!! Could not source: ${missing[*]}" >&2
    echo "   Add an SVG to $CUSTOM/ and re-run." >&2
    exit 1
fi

# Rewrite the gresource manifest.
{
    echo '<?xml version="1.0" encoding="UTF-8"?>'
    echo '<!-- Auto-generated by tools/gen-icon-gresource.sh; do not edit by hand.'
    echo '     Every symbolic icon Hylki names, under its plain name: the user'"'"'s'
    echo '     icon theme draws those it has, these the rest. Embedded in the'
    echo '     binary via build.rs. -->'
    echo '<gresources>'
    echo '  <gresource prefix="/co/hyprlab/Hylki">'
    for f in $(cd "$DST" && ls *.svg | sort); do
        echo "    <file>icons/scalable/actions/$f</file>"
    done
    echo '  </gresource>'
    echo '</gresources>'
} > "$ROOT/resources/hylki.gresource.xml"

echo "==> Bundled ${#names[@]} icons; wrote resources/hylki.gresource.xml"
